version: '3.6'
services:
  mapproxy:
    container_name: mapproxy
    env_file: .env
    environment:
      VIRTUAL_HOST: ${MAPPROXY_VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
      NETWORK_ACCESS: internal
      LETSENCRYPT_HOST: ${MAPPROXY_VIRTUAL_HOST}
      LETSENCRYPT_MAIL: ${MY_EMAIL}
#    volumes:
#      - mapproxy_files:/srv/mapproxy
    restart: unless-stopped
    networks:
      - proxy_net
      - couchdb_net
# When not using a proxy, I need to expose the port directly on the host
    ports:
      - "8080:8080"
#    expose:
#      - "8080"
    image: wildsong/mapproxy:latest
    build:
      context: .

  db:
    container_name: mapproxy-db
    image: couchdb:latest
    env_file: .env
    environment:
      VIRTUAL_HOST: ${COUCHDB_VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      NETWORK_ACCESS: internal
      LETSENCRYPT_HOST: ${COUCHDB_VIRTUAL_HOST}
      LETSENCRYPT_MAIL: ${MY_EMAIL}
      COUCHDATA: /opt/couchdb/data
      COUCHDB_USER: ${DB_USER}
      COUCHDB_SECRET: ${DB_PASSWORD}
    networks:
      couchdb_net:
        aliases:
          - couchdb
    ports:
      - "5984:5984"
    volumes:
      - db_data:/opt/couchdb/data
    restart: unless-stopped

volumes:
#  mapproxy_files:
#      name: mapproxy_files

  db_data:
     name: mapproxy_couchdb_data

networks:
  # This is a network we share with our reverse proxy
  proxy_net:
    name: proxy_net
    # Won't be created or destroyed with docker-compose up|down
    external: true

  # This network is only used for database access
  couchdb_net:
    name: couchdb_net
