version: '3.6'
services:
  mapproxy:
    container_name: mapproxy
    env_file: .env
    environment:
      VIRTUAL_HOST: ${MAPPROXY_VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
      NETWORK_ACCESS: internal
      LETSENCRYPT_HOST: ${MAPPROXY_VIRTUAL_HOST}
      LETSENCRYPT_MAIL: ${MY_EMAIL}
    volumes:
      - mapproxy_config:/srv/mapproxy/config
      - mapproxy_cache:/srv/mapproxy/cache
    restart: unless-stopped
    networks:
      proxy_net:
        aliases:
          - mapproxy
      database_net:
    expose:
      - "8080"
    image: wildsong/mapproxy:latest
    build:
      context: .
      dockerfile: Dockerfile.mapproxy

  db:
    container_name: mapproxy_couchdb
    image: couchdb:latest
    env_file: .env
    environment:
      VIRTUAL_HOST: ${COUCHDB_VIRTUAL_HOST}
      VIRTUAL_PORT: 5984
      LETSENCRYPT_HOST: ${COUCHDB_VIRTUAL_HOST}
      LETSENCRYPT_MAIL: ${MY_EMAIL}
      NETWORK_ACCESS: internal
      COUCHDATA: /opt/couchdb/data
      COUCHDB_USER: ${DB_USER}
      COUCHDB_SECRET: ${DB_PASSWORD}
    networks:
      proxy_net:
        aliases:
          - couchdb
      database_net:
        aliases:
          # N.B. This name is used in the URLs in the mapproxy configuration files.
          - couchdb 
    ports:
      - "5984:5984"
    expose:
      - "5984"
    volumes:
      - db_data:/opt/couchdb/data
    restart: unless-stopped

volumes:
  mapproxy_config:
      name: mapproxy_config
  mapproxy_cache:
        name: mapproxy_cache
  db_data:
     name: mapproxy_couchdb_data

networks:
  proxy_net:
    name: proxy_net
    external: true
  database_net:
    name: mapproxy_database_net
