version: '3.6'
services:
  mapproxy:
    container_name: mapproxy
    env_file: .env
    environment:
      VIRTUAL_HOST: ${MAPPROXY_VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
      NETWORK_ACCESS: internal
      LETSENCRYPT_HOST: ${MAPPROXY_VIRTUAL_HOST}
      LETSENCRYPT_MAIL: ${MY_EMAIL}
    volumes:
      - mapproxy_config:/srv/mapproxy/config
    restart: unless-stopped
    networks:
      proxy_net:
        aliases:
          - mapproxy
      database_net:
    expose:
      - "8080"
    image: wildsong/mapproxy:latest
    build:
      context: .
      dockerfile: Dockerfile.mapproxy
    # This will direct logging to the host machine
    logging:
      driver: syslog

# We're not going to expose this service on the Internet,
# so it's on a separate network. 
  db:
    container_name: mapproxy_couchdb
    image: couchdb:latest
    env_file: .env
    environment:
      NETWORK_ACCESS: internal
      COUCHDATA: /opt/couchdb/data
      COUCHDB_USER: ${DB_USER}
      COUCHDB_SECRET: ${DB_PASSWORD}
    networks:
      database_net:
        aliases:
          # N.B. This name is used in the URLs in the mapproxy configuration files.
          - couchdb 
    ports:
      - "5984:5984"
    expose:
      - "5984"
    volumes:
      - db_data:/opt/couchdb/data
    restart: unless-stopped
    # This will direct logging to the host machine
    logging:
      driver: syslog

volumes:
  mapproxy_config:
      name: mapproxy_config
  db_data:
     name: mapproxy_couchdb_data

networks:
  proxy_net:
    name: proxy_net
    external: true
  database_net:
    name: mapproxy_database_net
