services:
  # Please leave demo mode turned on, it makes debugging services much easier.
  demo:
  wms:
    md:
      title: Clatsop County MapProxy
      abstract: Proxy of outside services

globals:
  cache:
    base_dir: '/srv/mapproxy/cache_data'
    lock_dir: '/src/mapproxy/cache_data/locks'
    tile_lock_dir: '/src/mapproxy/cache_data/tile_locks'

  image:
    formats:
      image/png:
        resampling_method: bilinear
        transparent: true

      image/jpg:
        resampling_method: bilinear
        encoding_options:
          # default is 90
          jpeg_quality: 80
      


      